"""empty message

Revision ID: 01024938206c
Revises: c0cef2cf65c4
Create Date: 2020-07-06 17:59:36.379187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01024938206c'
down_revision = 'c0cef2cf65c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
